<?php

function krsa_ta_csv_menu() {
  $items = array();
  $items['ta_csv'] = array(
    'title' => 'TA to CSV',
    'page callback' => 'krsa_ta_csv',
    'access arguments' => array(true),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

function krsa_ta_csv() {
  
  $url_base = 'https://www.kretinga.lt';
  $url_of_all_tarspr = 'https://www.kretinga.lt/node/251';
  $html_obj = file_get_html($url_of_all_tarspr);
  $node_html_obj = $html_obj->getElementById("node-251");
  
  $links = array();
  foreach($node_html_obj->find('li.leaf a') as $link) {
    $url = $url_base . $link->href;
    $links[] = $url;
    $all_ta_info[] = _get_ta_rows_content($url);
  }
  
  $parsed_data = _parse_all_ta_info($all_ta_info);
  kpr($parsed_data);
  
  // Release resources to avoid memory leak in some versions.
  $html_obj->clear();
  unset($html_obj);

  return 'TEST';
}

/**
 * Function parse raw array data from crawler to strict structure:
 * - new row per month / crawled page
 * - each sub row can be main document or extra document (attachment to main doc)
 * - each document can have link to file or link can be empty
 * - each document must have title
 * @param array $all_ta_info - multidimensional array of scrapped tables rows
 * @return array - multidimensional parsed structured array
 */
function _parse_all_ta_info($all_ta_info) {

  $parsed_data = array();
  foreach($all_ta_info as $key => $ta_per_month) {
    $count_a = count($ta_per_month['a']);
    $count_p = count($ta_per_month['p']);
    
    $ta_per_month_result = $ta_per_month['a'];
    if ($count_p > $count_a) {
      // if some records don't have links to file
      
      $tmp_a = array();
      foreach ($ta_per_month['a'] as $item_a) {
        $tmp_a[] = $item_a['title'];
      }
      
      // create array with records without links
      $arr1 = $ta_per_month['p'];
      $arr2 = $tmp_a;
      $without_links_arr = _array_diff_by_str_val($arr1, $arr2);
      
      // insert records without links in array whose records are only with links
      foreach ($without_links_arr as $index => $value) {
        array_splice($ta_per_month_result, $index, 0, array($value));
      }
    } else {
      // all records have links - nothing to do.      
    }
    $parsed_data[$key] = $ta_per_month_result;
  }
  return $parsed_data;
}

// create array with records without links
// similar to array_diff()
function _array_diff_by_str_val($arr1, $arr2) {
  $pos_shift = 0;
  $array_diff = array();
  foreach ($arr1 as $pos => $item) {
    if (isset($arr2[$pos + $pos_shift])) {
      if (!($item == $arr2[$pos + $pos_shift])) {
        $array_diff[$pos] = array('title' => $item, 'href' => '');
        $pos_shift--;
      }
    }
    else {
      $array_diff[$pos] = array('title' => $item, 'href' => '');
    }
  }
  return $array_diff;
}

// get documents list from one page (T2 case one page = one months)
// table rows are splitted by <a> and <p> tags and recorded to array fiels
function _get_ta_rows_content($url) {
  $html_obj_ta_page = file_get_html($url);
  $node_html_obj_ta = $html_obj_ta_page->getElementById("main-inner");
  
  $table_rows_a = $node_html_obj_ta->find('table.spr tr.tablerow a');
  
  $rows = array();
  foreach($table_rows_a as $row) {
    $title = trim(str_replace('&nbsp;', ' ', $row->plaintext));
    $link = $row->href;
    $rows[] = array('title' => $title, 'href' => $link);
  }
  
  $table_rows_p = $node_html_obj_ta->find('table.spr tr.tablerow p');
  
  $rows_p = array();
  foreach($table_rows_p as $row) {
    $title = trim(str_replace('&nbsp;', ' ', $row->plaintext)); //->find('tr');
    $rows_p[] = $title;
  }
  
  $html_obj_ta_page->clear();
  unset($html_obj_ta_page);
  
  return array('a' => $rows, 'p' => $rows_p);
}